env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

task:
    name: zeta
    timeout_in: 120m
    container:
      dockerfile: Dockerfile
      cpu: 8
      memory: 24G
    download_ccache_background_script:
      - ./download_ccache
    sync_script:
      - ./sync
    monitor_background_script:
      - ./monitor
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
