task:
    name: rom
    timeout_in: 4h
    container:
      dockerfile: Dockerfile
      cpu: 8
      memory: 32G
    environment:
      CIRRUS_CLONE_DEPTH: 1
      CIRRUS_WORKING_DIR: "/tmp/ci"
    download_ccache_background_script:
      - bash download_ccache.sh
    sync_script:
      - bash sync.sh
    monitor_background_script:
      - bash monitor.sh
    build_script:
      - bash build.sh
    upload_ccache_script:
      - bash upload_ccache.sh
